### ISSUE TITLE
Issue with creating SSE Kubernetes Services

### ISSUE THREAD

**Issue by ChrisJBurns** [stacklok/toolhive#295]
## Description

I am installing the `mkp` MCP service inside of a Kind cluster and am seeing issues with the proxy pod creating the headless service.

```yaml
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: mkp
  namespace: toolhive-system
spec:
  image: ghcr.io/stackloklabs/mkp/server
  transport: sse
  port: 8080
  permissionProfile:
    type: builtin
    name: network
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
```

The error I am getting is:
`8:58PM ERR &{0x40000b8180}, failed to set up transport: failed to create container: failed to create headless service: failed to apply service: Service "mkp" is invalid: spec.clusterIPs[0]: Invalid value: []string{"None"}: may not change once set`.
 
It appears that the issue seems to be that we create a [SVC via the Operator](https://github.com/StacklokLabs/toolhive/blob/main/cmd/thv-operator/controllers/mcpserver_controller.go#L136-L157)  and then in the toolhive code we create a [headless SVC](https://github.com/StacklokLabs/toolhive/blob/main/pkg/container/kubernetes/client.go#L326) if the transport type is `sse`. 

This ends up with the scenario where the toolhive container is trying to create a service with `ClusterIP: None`, however because the SVC has already been created by the Operator, it errors because the `ClusterIP` field is immutable and cannot be changed.
