### ISSUE TITLE
The opanAPI spec it not generating enum for workload status

### ISSUE THREAD

**Issue by peppescg** [stacklok/toolhive#780]
Starting from this [enum ](https://github.com/stacklok/toolhive/blob/main/pkg/workloads/models.go#L15) the swagger created is translating it with:
```
 workloads.WorkloadStatus:
      description: Status is the current status of the workload.
      type: string
      x-enum-varnames:
      - WorkloadStatusRunning
      - WorkloadStatusStopped
      - WorkloadStatusError
      - WorkloadStatusStarting
      - WorkloadStatusUnknown
```
Probably it should be `enum:` rather than `x-enum-varnames:`
