### ISSUE TITLE
Add client configuration support for Continue

### ISSUE THREAD

**Issue by danbarr** [stacklok/toolhive#832]
## Proposal

Continue is a popular IDE extension for both VS Code and JetBrains IDEs. It supports both SSE and Streamable HTTP transports.

I've confirmed that manual configuration works with ToolHive-run MCP servers using either protocol.

Proposing that we add Continue as a supported client for automatic configuration.

## Details

Continue's user-scoped MCP servers are configured in the `~/.continue/config.yaml` file on all platforms. This single file is read by both their VS Code and JetBrains plugins. SSE servers are defined in the `mcpServers` block.

We'll need to add YAML editing support alongside the current JSON support.

Example SSE entry:

```yaml
mcpServers:
  - name: fetch
    type: sse
    url: http://127.0.0.1:40880/sse#fetch
```

Example Streamable HTTP entry:

```yaml
mcpServers:
  - name: osv
    type: streamable-http
    url: http://127.0.0.1:22089/mcp
```

Reference: https://docs.continue.dev/customize/deep-dives/mcp#transport-types
