### ISSUE TITLE
Issue Starting MKP Server on EKS Cluster with Toolhive Operator

### ISSUE THREAD

**Issue by adityaculvii** [stacklok/toolhive#902]
I’m currently working with an EKS cluster running version v1.33.0, using the Toolhive operator in its default cluster mode (version 0.1.0).

I installed the MKP server using the manifest from this repository:
https://raw.githubusercontent.com/stacklok/toolhive/main/examples/operator/mcp-servers/mcpserver_mkp.yaml

However, I'm encountering the following error:

**Error: failed to start transport: target port not set for HTTP transport**

I also attempted to use the fetch MCP server with stdio/sse both transports, but it failed to connect as well.

Any insights or suggestions to resolve this issue would be appreciated.

**Comment by ChrisJBurns** [comment]
Thanks @adityaculvii  I'll take a look! I'm also getting the same error, I'm assuming its a regression in the underlying toolhive cli. Will post more here when Ive dug a bit deeper

**Comment by ChrisJBurns** [comment]
Found the culprit. it appears we are defaulting the [targetPort to `0`](https://github.com/stacklok/toolhive/commit/106ea358c15c94db0841d8c2537ca6c1dead34bc#diff-38fecb0789c3417dfc50bf25d6986584a8821f57fc4ff0474c1f2ad4123fb3a0) in the lower level transport layer as part of the ingress proxy for the docker runtime and because it shared an interface with the kubernetes code, the `int` is being defaulted to `0`. I'll have a chat with some of the folks and get a fix up speedily!

**Comment by adityaculvii** [comment]
Hi @ChrisJBurns  Thanks for the update. Could we please address this issue? It’s currently blocking our deployment.

Also, I noticed the note mentioning that Toolhive is still experimental and not recommended for production. However, our team is evaluating Toolhive for potential use in a production environment. Do you think this is advisable, or do you have any recommendations regarding its setup?

**Comment by ChrisJBurns** [comment]
This is still an issue as reported in https://github.com/stacklok/toolhive/issues/924. We will track under #924 to avoid duplicate issues

**Comment by craigmcl** [comment]
Hi @adityaculvii, happy to have the discussion re production use.  Might be easiest if you mail me at craig@stacklok.com - it would be helpful to understand your specific use case and specific timeframe before we make a recommendation.

**Comment by ChrisJBurns** [comment]
@adityaculvii  For awareness, we've fix this issue in the latest [`0.1.2`](https://github.com/stacklok/toolhive/releases/tag/v0.1.2) version.

**Comment by adityaculvii** [comment]
Hi @ChrisJBurns thanks for the update ,i just updated operator to use 0.1.2 version , still facing the same issue , am i missing something?

**Comment by ChrisJBurns** [comment]
Apologies, I mistakenly edited your comment as opposed to replied with a new one.

Have you amended the operator deployment chart so that it uses the `0.1.2` image of toolhive? https://github.com/stacklok/toolhive/blob/main/deploy/charts/operator/values.yaml#L20. The fix was applied to the toolhive image

**Comment by adityaculvii** [comment]
Hi @ChrisJBurns , thank you — it's working now!

I have one more question. I was testing fetch **mcp** using the documentation here: https://docs.stacklok.com/toolhive/tutorials/toolhive-operator

At Step 3, the provided MCP uses stdio as the transport method. But in Step 5, while setting it up in settings.json, it mentions using sse as the transport.

When I try that, I'm getting the following warning:

`405 status sending message to https://xxx/sse#fetch , will attempt to fall back to legacy SSE (using ALB Ingress)`

Here are some logs from the proxy pod:

```
3:45PM INF Writing to container stdin  
3:45PM INF Wrote to container stdin  
3:45PM INF Messages processed  
E0702 15:45:52.421262       1 v2.go:104] "Unhandled Error" err="EOF" logger="UnhandledError"  
3:45PM INF Process incoming messages and sending message to container  
3:45PM INF Writing to container stdin  
3:48PM INF Received JSON-RPC message: *jsonrpc2.Request  
3:53PM INF Client 5eddb695-8374-43e0-9ced-259ea2d84e6a disconnected  
```

Could you clarify whether sse is the correct transport, or should it remain stdio? and why is this happening?

**Comment by ChrisJBurns** [comment]
@adityaculvii Yeah so ToolHive exposes MCP servers to agents over SSE. If you have an `stdio` MCP Server, the communication between Toolhive and the MCP server is `stdio` but to your agents, it is SSE. This diagram should describe it a bit more https://docs.stacklok.com/toolhive/guides-k8s/run-mcp-k8s#stdio-transport-flow

**Comment by adityaculvii** [comment]
Hi @ChrisJBurns  I thought so too — but why is it failing?

I've shared the proxy logs above, along with the 405 error code and the message I'm seeing in VS Code. Do you have any idea what might be causing this issue?

**Comment by ChrisJBurns** [comment]
@adityaculvii  How are you setting up your port forward?

**Comment by adityaculvii** [comment]
@ChrisJBurns 8080 , command i used

`kubectl port-forward svc/mcp-fetch-proxy -n <namespace>  8080:8080`

**Comment by adityaculvii** [comment]
initially health check endpoint response was this

`{"status":"healthy","timestamp":"2025-07-02T15:48:00.471784228Z","version":{"version":"v0.1.2","commit":"a5a2e28aa057ddc5810dd30790ccb4fe262dc8fb","build_date":"2025-07-02 15:49:30 +0200","go_version":"go1.24.1","platform":"linux/amd64"},"transport":"stdio","mcp":{"available":true,"response_time_ms":0,"last_checked":"2025-07-02T15:48:00.471796199Z"}}`



Now, its this
`
{"status":"degraded","timestamp":"2025-07-02T18:26:17.65756157Z","version":{"version":"v0.1.2","commit":"a5a2e28aa057ddc5810dd30790ccb4fe262dc8fb","build_date":"2025-07-02 15:49:30 +0200","go_version":"go1.24.1","platform":"linux/amd64"},"transport":"stdio","mcp":{"available":false,"error":"message channel is full or closed","last_checked":"2025-07-02T18:26:17.6575738Z"}}`

**Comment by ChrisJBurns** [comment]
@adityaculvii If you delete both the mcp server pod and the proxy pod, and let them both get recreated, does it still error with message channel full?

**Comment by JAORMX** [comment]
Reopening til we get a resolution

**Comment by JAORMX** [comment]
Although, is this another issue? The channel being full

**Comment by ChrisJBurns** [comment]
Yeah I'm trying to get to a point where its replicated then I'll open another issue for it.

**Comment by adityaculvii** [comment]
Hi @ChrisJBurns @JAORMX Thanks for the quick response. Do we have an estimated timeline for this?
Also, for deploying any **custom MCP**, I just need to update the spec.image field — is that correct?
How is scaling handled in this setup?
And where is the proxy container being defined?


```
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: fetch
  namespace: development # Can be any namespace
spec:
  image: docker.io/mcp/fetch
  transport: stdio
  port: 8080
  permissionProfile:
    type: builtin
    name: network
  podTemplateSpec:
    spec:
      containers:
        - name: mcp # This name must be "mcp"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: false # Allows the MCP container to run as root
            runAsUser: 0
            capabilities:
              drop:
                - ALL
          resources: # These resources apply to the MCP container
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '100m'
              memory: '128Mi'
      securityContext:
        runAsNonRoot: true # The pod itself can run as a non-root user
        seccompProfile:
          type: RuntimeDefault
  resources: # These resources apply to the proxy container
    limits:
      cpu: '100m'
      memory: '128Mi'
    requests:
      cpu: '50m'
      memory: '64Mi'
```

**Comment by adityaculvii** [comment]
Hi @ChrisJBurns @JAORMX @craigmcl I’d really appreciate it if you could respond to the query above. Thank you!

**Comment by ChrisJBurns** [comment]
@adityaculvii  Apologies for the late response, I must have missed the notification on your previous comment. 

>Also, for deploying any custom MCP, I just need to update the spec.image field — is that correct?

That's correct, you would change it to an image that is able to be deployed onto your cluster nodes

>How is scaling handled in this setup?

If you mean scaling as in horizontally, there is no mechanism at the moment that does this automatically. For `stdio` servers there are a one to one mapping with the proxyrunner - this is because of it's attach/detach nature for stdin and stdout. We will be looking into how we can smartly scale `stdio` servers based on requests, but we have nothing set in stone at the moment.

> And where is the proxy container being defined?

The proxy container itself is mostly hidden from you from a CRD perspective. You can override [some of the resources](https://github.com/stacklok/toolhive/blob/main/cmd/thv-operator/controllers/mcpserver_controller.go#L538) that it uses regarding CPU/MEM, labels/annotations etc. But its not completely overridable at the moment.


Regarding your root issue around the channel being full, I couldn't actually reproduce this on my side. Were you able to restart the pods to see if it was reproduced?

**Comment by adityaculvii** [comment]
Hi @ChrisJBurns , thanks for the quick response!

Would implementing HPA on the proxy deployment handle the scaling effectively?

Also, could you explain how streamable HTTP transport works and how it can be implemented?

**Comment by ChrisJBurns** [comment]
@adityaculvii  HPA wouldn't really be the best solution due to the 1:1 mapping between proxyrunner and mcp server. STDIO itself adds a different layer of complexity to container workloads. We are looking at request based scaling but nothing is set is stone yet. This is partly why we'd recommend using SSE/StreamableHTTP servers longer term because you don't have the same challenges as you do with stdio servers.

On the StreamableHTTP question, do you mean how it works on the MCP level or how we do it in ToolHive? MCP has a good [writeup of this](https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#streamable-http)  if it's the former.

**Comment by adityaculvii** [comment]
Hi @ChrisJBurns thank you , if we use SSE/StreamableHTTP , what would be scaling setup be like? and how do we do StreamableHTTP in toolhive?

**Comment by adityaculvii** [comment]
Hi @ChrisJBurns , please answer above query ,

I tried using fetch today and encountered some issues depending on the transport method.

**Custom Resource:**

```
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: fetch
  namespace: toolhive
spec:
  image: docker.io/mcp/fetch
  transport: stdio
  port: 8080
  permissionProfile:
    type: builtin
    name: network
  podTemplateSpec:
    spec:
      containers:
        - name: mcp # This name must be "mcp"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: false # Allows the MCP container to run as root
            runAsUser: 0
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true # The pod itself can run as a non-root user
        seccompProfile:
          type: RuntimeDefault
```

Issue with sse transport:

I'm getting the following error when using sse:

```
Error: failed to set up transport: failed to create container: failed to create headless service: failed to apply service: 
Service "mcp-fetch-headless" is invalid: spec.clusterIPs[0]: Invalid value: "None": may not be set to 'None' for NodePort services

```
Issue with stdio transport:

With stdio, I encountered this runtime error:

`RuntimeError: Received request before initialization was complete`

Additional logs:

```
Unhandled Error: EOF
Error code: 405 when sending message to https://<domain>/sse#fetch
Will attempt to fall back to legacy SSE

```
Let me know if there's anything I might be missing or need to configure differently.
